name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.11'

jobs:
  python-ci:
    name: Python CI (${{ github.actor }} - ${{ github.sha }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install coverage flake8 pytest

      - name: Run tests with pytest
        continue-on-error: true
        run: |
          coverage run -m pytest

      - name: Generate coverage report
        run: |
          coverage report

      - name: Check code style (flake8)
        continue-on-error: true
        run: |
          flake8 .

      - name: Check code complexity (flake8)
        continue-on-error: true
        run: |
          flake8 . --max-complexity=10

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: python-source
          path: |
            **/*.py